const actions = {
  LOAIMAUPHIEU_GET_INIT_DATA_REQUEST: 'LOAIMAUPHIEU_GET_INIT_DATA_REQUEST',
  LOAIMAUPHIEU_GET_INIT_DATA_REQUEST_SUCCESS:
    'LOAIMAUPHIEU_GET_INIT_DATA_REQUEST_SUCCESS',
  LOAIMAUPHIEU_GET_INIT_DATA_REQUEST_ERROR:
    'LOAIMAUPHIEU_GET_INIT_DATA_REQUEST_ERROR',

  LOAIMAUPHIEU_GET_ALL_DATA_REQUEST: 'LOAIMAUPHIEU_GET_ALL_DATA_REQUEST',
  LOAIMAUPHIEU_GET_ALL_DATA_REQUEST_SUCCESS:
    'LOAIMAUPHIEU_GET_ALL_DATA_REQUEST_SUCCESS',
  LOAIMAUPHIEU_GET_ALL_DATA_REQUEST_ERROR:
    'LOAIMAUPHIEU_GET_ALL_DATA_REQUEST_ERROR',

  getData: (filterData) => ({
    type: actions.LOAIMAUPHIEU_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),

  getAll: (filterData) => ({
    type: actions.LOAIMAUPHIEU_GET_ALL_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
