const actions = {
  LOAIDITICH_GET_INIT_DATA_REQUEST:
    'LOAIDITICH_GET_INIT_DATA_REQUEST',
  LOAIDITICH_GET_INIT_DATA_REQUEST_SUCCESS:
    'LOAIDITICH_GET_INIT_DATA_REQUEST_SUCCESS',
  LOAIDITICH_GET_INIT_DATA_REQUEST_ERROR:
    'LOAIDITICH_GET_INIT_DATA_REQUEST_ERROR',

  getData: (filterData) => ({
    type: actions.LOAIDITICH_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
