const actions = {
  PHANLOAI_GET_INIT_DATA_REQUEST: 'PHANLOAI_GET_INIT_DATA_REQUEST',
  PHANLOAI_GET_INIT_DATA_REQUEST_SUCCESS:
    'PHANLOAI_GET_INIT_DATA_REQUEST_SUCCESS',
  PHANLOAI_GET_INIT_DATA_REQUEST_ERROR: 'PHANLOAI_GET_INIT_DATA_REQUEST_ERROR',

  getData: (filterData) => ({
    type: actions.PHANLOAI_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
