const actions = {
  CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST:
    'CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST',
  CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST_SUCCESS:
    'CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST_SUCCESS',
  CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST_ERROR:
    'CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST_ERROR',

  getData: (filterData) => ({
    type: actions.CAPDITICHXEPHANG_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
