const actions = {
  DONVITINH_GET_INIT_DATA_REQUEST: 'DONVITINH_GET_INIT_DATA_REQUEST',
  DONVITINH_GET_INIT_DATA_REQUEST_SUCCESS:
    'DONVITINH_GET_INIT_DATA_REQUEST_SUCCESS',
  DONVITINH_GET_INIT_DATA_REQUEST_ERROR:
    'DONVITINH_GET_INIT_DATA_REQUEST_ERROR',

  getData: (filterData) => ({
    type: actions.DONVITINH_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
