const actions = {
  DMTHUVIEN_GET_INIT_DATA_REQUEST: 'DMTHUVIEN_GET_INIT_DATA_REQUEST',
  DMTHUVIEN_GET_INIT_DATA_REQUEST_SUCCESS:
    'DMTHUVIEN_GET_INIT_DATA_REQUEST_SUCCESS',
  DMTHUVIEN_GET_INIT_DATA_REQUEST_ERROR:
    'DMTHUVIEN_GET_INIT_DATA_REQUEST_ERROR',
  DMTHUVIEN_GET_ALL_DATA_REQUEST: 'DMTHUVIEN_GET_ALL_DATA_REQUEST',
  DMTHUVIEN_GET_ALL_DATA_REQUEST_SUCCESS:
    'DMTHUVIEN_GET_ALL_DATA_REQUEST_SUCCESS',
  DMTHUVIEN_GET_ALL_DATA_REQUEST_ERROR:
    'DMTHUVIEN_GET_ALL_DATA_REQUEST_ERROR',
  getData: (filterData) => ({
    type: actions.DMTHUVIEN_GET_INIT_DATA_REQUEST,
    payload: {filterData},
  }),
  getAll: (filterData) => ({
    type: actions.DMTHUVIEN_GET_ALL_DATA_REQUEST,
    payload: {filterData},
  }),
};

export default actions;
